#!/usr/bin/env python3
"""Build the browser's verified fast-mode cache from approved workbooks.

The cache contains only each workbook's own default age, gender, face amount,
declared rate, and mandatory dividend option.  The browser rejects it whenever
any one of those inputs or the workbook hash differs, and uses the Calc API.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import insurance_calculation_server as service


def build_cache(source_dir: Path) -> dict[str, dict]:
    original_root = service.ROOT
    service.ROOT = source_dir
    try:
        profiles: dict[str, dict] = {}
        for workbook in sorted(source_dir.glob("*.xlsx")):
            if not service.has_financing_filename(workbook.name):
                continue
            profile = service.extract_profile(workbook)
            if profile["webCode"] in service.BUILT_IN_SOURCE_CODES:
                profiles[profile["webCode"]] = profile
        missing = service.BUILT_IN_SOURCE_CODES.difference(profiles)
        if missing:
            raise SystemExit("missing approved workbooks: " + ", ".join(sorted(missing)))
        return {
            code: service.build_default_quote_cache(profiles[code])
            for code in sorted(profiles)
        }
    finally:
        service.ROOT = original_root


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate verified browser fast-mode quote cache.")
    parser.add_argument("--source-dir", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parent / "default_quote_cache_data.js")
    args = parser.parse_args()
    source_dir = args.source_dir.resolve()
    if not source_dir.is_dir():
        raise SystemExit(f"source directory does not exist: {source_dir}")
    cache = build_cache(source_dir)
    contents = (
        "// Generated by generate_default_quote_cache.py. Do not edit by hand.\n"
        "window.DEFAULT_POLICY_QUOTE_CACHE_BY_PRODUCT = Object.freeze(\n"
        + json.dumps(cache, ensure_ascii=False, separators=(",", ":"), indent=2)
        + "\n);\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(contents, "utf-8")
    print(f"Wrote {args.output} for {', '.join(sorted(cache))}")


if __name__ == "__main__":
    main()
