#!/usr/bin/env python3
"""Regression checks for the LibreOffice-backed premium-financing calculator."""

from __future__ import annotations

import copy
import argparse
import json
from pathlib import Path

import insurance_calculation_server as service


EXPECTED = {
    "ABA": {"age": 30, "gender": "male", "face": 95000, "rate": 4.35, "premium": 100291, "reference": 70720},
    "WEF": {"age": 19, "gender": "male", "face": 2000000, "rate": 4.15, "premium": 358380, "reference": 223007},
    "WJA": {"age": 1, "gender": "male", "face": 300000, "rate": 4.35, "premium": 30510, "reference": 24053},
    "WQ6": {"age": 19, "gender": "male", "face": 200000, "rate": 4.25, "premium": 135519, "reference": 95325},
    "WUS": {"age": 40, "gender": "male", "face": 1840000, "rate": 4.30, "premium": 500758, "reference": 359085},
}


def quote(profile: dict, expected: dict, rate: float | None = None) -> dict:
    return service.calculate_quote(profile, {
        "profileId": profile["id"],
        "age": expected["age"],
        "gender": expected["gender"],
        "faceAmount": expected["face"],
        "declaredRate": expected["rate"] if rate is None else rate,
    })


def load_fast_cache(path: Path) -> dict:
    contents = path.read_text("utf-8")
    prefix = "window.DEFAULT_POLICY_QUOTE_CACHE_BY_PRODUCT = Object.freeze("
    assert contents.startswith("// Generated by generate_default_quote_cache.py"), "快速快取必須由產製工具建立"
    assert prefix in contents and contents.rstrip().endswith(");"), "快速快取格式無效"
    payload = contents.split(prefix, 1)[1].strip()
    return json.loads(payload[:-2])


def assert_fast_cache_matches_quote(code: str, cache: dict, result: dict, profile: dict) -> None:
    assert cache["sourceHash"] == profile["sourceHash"], f"{code} 快速快取來源版本不符"
    assert cache["declaredRate"] == result["declaredRate"], f"{code} 快取宣告利率不符"
    assert cache["age"] == result["age"] and cache["gender"] == result["gender"], f"{code} 快取投保條件不符"
    assert cache["faceAmount"] == result["faceAmount"], f"{code} 快取保額不符"
    assert cache["dividendOption"] == service.DIVIDEND_OPTION_CONTINUE, f"{code} 快取給付方式不符"
    for field in ("premium", "tablePremium", "referenceCashValue"):
        assert abs(float(cache[field] or 0) - float(result[field] or 0)) <= 0.01, f"{code} 快取 {field} 不符"
    for field in ("benefitByYear", "cashValueByYear"):
        assert len(cache[field]) == len(result[field]) == 100, f"{code} 快取 {field} 年度長度不符"
        for year, (cached, calculated) in enumerate(zip(cache[field], result[field]), start=1):
            if cached is None or calculated is None:
                assert cached is None and calculated is None, f"{code} 快取 {field} 第 {year} 年空值不符"
            else:
                assert abs(float(cached) - float(calculated)) <= 0.01, f"{code} 快取 {field} 第 {year} 年不符"


def main() -> None:
    parser = argparse.ArgumentParser(description="Verify workbook-backed premium-financing calculations.")
    parser.add_argument("--source-dir", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--fast-cache", type=Path, default=Path(__file__).resolve().parent / "default_quote_cache_data.js")
    args = parser.parse_args()
    source_dir = args.source_dir.resolve()
    assert source_dir.is_dir(), f"來源目錄不存在：{source_dir}"
    original_root = service.ROOT
    service.ROOT = source_dir
    store = service.ProfileStore()
    try:
        store.bootstrap_workspace_sources()
        profiles = {item["webCode"]: item for item in store._profiles}
        assert set(EXPECTED).issubset(profiles), "五項來源商品未完整載入"
        fast_cache = load_fast_cache(args.fast_cache.resolve())

        for code, expected in EXPECTED.items():
            source_path = service.profile_source_path(profiles[code])
            source_hash_before = service.sha256_file(source_path)
            result = quote(profiles[code], expected)
            assert service.sha256_file(source_path) == source_hash_before, f"{code} 的來源建議書不應被重算流程修改"
            assert profiles[code]["dividendOption"] == service.DIVIDEND_OPTION_CONTINUE, f"{code} 未固定為持續增購保額"
            assert "dividendOption" in profiles[code]["inputCells"], f"{code} 找不到給付方式輸入格"
            assert result["dividendOption"] == service.DIVIDEND_OPTION_CONTINUE, f"{code} 回傳的給付方式不正確"
            assert abs(result["premium"] - expected["premium"]) <= 1, f"{code} 保費不符"
            assert abs(result["referenceCashValue"] - expected["reference"]) <= 1, f"{code} 融資參考現金價值不符"
            assert result["benefitByYear"][0] is not None, f"{code} 第一年保障不可為空"
            assert result["cashValueByYear"][19] is not None, f"{code} 第二十年現金價值不可為空"
            assert_fast_cache_matches_quote(code, fast_cache[code], result, profiles[code])
            print(f"PASS {code}: premium={result['premium']:,.0f}, reference={result['referenceCashValue']:,.0f}, fast cache verified")

        aba = quote(profiles["ABA"], EXPECTED["ABA"])
        assert abs(aba["benefitByYear"][19] - 216607) <= 1, "ABA 持續增購保額後的第 20 年保障不符"
        assert abs(aba["cashValueByYear"][19] - 222779.85) <= 0.01, "ABA 持續增購保額後的第 20 年現金價值不符"
        print("PASS ABA forced to 第7年起持續增購保額")

        store.cache_quote(profiles["ABA"]["id"], aba)
        shared_data = service.quote_data_payload(profiles["ABA"])
        assert shared_data["sourceHash"] == profiles["ABA"]["sourceHash"], "共用商品資料來源版本不符"
        shared_aba = next((item for item in shared_data["quotes"] if service.quote_cache_key(item) == service.quote_cache_key(aba)), None)
        assert shared_aba is not None, "Calc 結果未加入共用商品資料"
        assert_fast_cache_matches_quote("ABA shared", shared_aba, aba, profiles["ABA"])
        javascript = service.quote_data_javascript(profiles["ABA"])
        assert f'window.{service.QUOTE_DATA_GLOBAL_NAME}' in javascript, "商品資料 JS 未正確發布"
        public_aba = next(item for item in store.public_profiles() if item["id"] == profiles["ABA"]["id"])
        assert public_aba["quoteDataPath"].endswith(f'{profiles["ABA"]["id"]}.js'), "商品資料 JS 路徑不正確"
        assert public_aba["quoteDataVersion"], "商品資料 JS 版本遺失"
        print("PASS shared browser quote-data JS cache")

        wus = profiles["WUS"]
        higher = quote(wus, EXPECTED["WUS"], 4.30)
        lower = quote(wus, EXPECTED["WUS"], 4.20)
        assert higher["cashValueByYear"][19] > lower["cashValueByYear"][19], "WUS 宣告利率提高後第 20 年現金價值應上升"
        assert higher["benefitByYear"][19] > lower["benefitByYear"][19], "WUS 宣告利率提高後第 20 年保障應上升"
        assert higher["referenceCashValue"] == lower["referenceCashValue"], "投保日融資參考現金價值不應受宣告利率影響"
        print("PASS WUS declared-rate sensitivity and fixed inception financing reference")

        saved = copy.deepcopy(store._profiles)
        try:
            probe = copy.deepcopy(profiles["WJA"])
            probe["name"] = "國泰人壽匯入驗證新商品"
            probe["normalizedName"] = service.normalized_text(probe["name"])
            probe["id"] = "product-import-verification"
            probe["sourceCode"] = "VERIFY"
            probe["webCode"] = "VERIFY"
            _, action = store.upsert(probe, persist=False)
            assert action == "created", "新商品名稱應新增商品"
            probe["declaredRate"] = 0.049
            probe["sourceHash"] = "verification-changed-source-hash"
            _, action = store.upsert(probe, persist=False)
            assert action == "updated", "同名商品應更新既有條件"
            print("PASS import naming rule: new name creates, same name updates")
        finally:
            store._profiles = saved
            store._save()

        assert not service.has_financing_filename("一般建議書.xlsx"), "檔名限制失效"
        assert service.has_financing_filename("商品_保費融資.xlsx"), "檔名限制誤拒"
        print("PASS filename gate")
        print("ALL VERIFICATIONS PASSED")
    finally:
        service.ROOT = original_root


if __name__ == "__main__":
    main()
